// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkCcG8bCmpikDfOQwCL1TBvEXJPcTW-9Q',
    appId: '1:431047351036:web:14ceb8579c3c162ac21579',
    messagingSenderId: '431047351036',
    projectId: 'sportshub-d5507',
    authDomain: 'sportshub-d5507.firebaseapp.com',
    storageBucket: 'sportshub-d5507.firebasestorage.app',
    measurementId: 'G-1H40EE8RF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARTl7fu_4L-wEM0EpW_AabaMYwyosaLcg',
    appId: '1:431047351036:android:cf45267771a067eec21579',
    messagingSenderId: '431047351036',
    projectId: 'sportshub-d5507',
    storageBucket: 'sportshub-d5507.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4k7htoq6DtGJ7anKMtcbYBhhy22vsCqs',
    appId: '1:431047351036:ios:1dd621f8e4a98250c21579',
    messagingSenderId: '431047351036',
    projectId: 'sportshub-d5507',
    storageBucket: 'sportshub-d5507.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4k7htoq6DtGJ7anKMtcbYBhhy22vsCqs',
    appId: '1:431047351036:ios:1dd621f8e4a98250c21579',
    messagingSenderId: '431047351036',
    projectId: 'sportshub-d5507',
    storageBucket: 'sportshub-d5507.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkCcG8bCmpikDfOQwCL1TBvEXJPcTW-9Q',
    appId: '1:431047351036:web:ca4eb95ebf854d94c21579',
    messagingSenderId: '431047351036',
    projectId: 'sportshub-d5507',
    authDomain: 'sportshub-d5507.firebaseapp.com',
    storageBucket: 'sportshub-d5507.firebasestorage.app',
    measurementId: 'G-Y9RESML29Q',
  );
}
